import { describe, it, expect, vi } from 'vitest';

import { collectRustDeps, parseCargoLock } from '@/lib/manifests/rust';

type Octokit = Parameters<typeof collectRustDeps>[0];

function octokitWith(files: Record<string, string>): Octokit {
  const getContent = vi.fn(async ({ path }: { path: string }) => {
    if (path in files) {
      return { data: { content: Buffer.from(files[path]).toString('base64') } };
    }
    throw new Error('404');
  });
  return { rest: { repos: { getContent } } } as unknown as Octokit;
}

const CRATES_IO = 'registry+https://github.com/rust-lang/crates.io-index';

const lock = `# This file is automatically @generated by Cargo.
version = 3

[[package]]
name = "app"
version = "0.1.0"
dependencies = [
 "serde",
 "local-lib",
]

[[package]]
name = "local-lib"
version = "0.2.0"

[[package]]
name = "serde"
version = "1.0.197"
source = "${CRATES_IO}"
checksum = "abc"

[[package]]
name = "from-git"
version = "0.3.0"
source = "git+https://github.com/x/from-git?branch=main#deadbeef"

[[package]]
name = "private-crate"
version = "4.0.0"
source = "registry+https://my.registry.example/index"

[[package]]
name = "tokio"
version = "1.36.0"
source = "${CRATES_IO}"

[metadata]
name = "not-a-package"
version = "9.9.9"
source = "${CRATES_IO}"
`;

describe('parseCargoLock', () => {
  it('returns exact versions of crates.io packages only', () => {
    expect(parseCargoLock(lock)).toEqual([
      { name: 'serde', version: '1.0.197' },
      { name: 'tokio', version: '1.36.0' },
    ]);
  });

  it('skips workspace members and path dependencies (no source)', () => {
    const names = parseCargoLock(lock).map((d) => d.name);
    expect(names).not.toContain('app');
    expect(names).not.toContain('local-lib');
  });

  it('skips git sources', () => {
    expect(parseCargoLock(lock).map((d) => d.name)).not.toContain('from-git');
  });

  it('skips alternate registries', () => {
    expect(parseCargoLock(lock).map((d) => d.name)).not.toContain('private-crate');
  });

  it('accepts the sparse crates.io index source', () => {
    const sparse = `[[package]]\nname = "rand"\nversion = "0.8.5"\nsource = "sparse+https://index.crates.io/"\n`;
    expect(parseCargoLock(sparse)).toEqual([{ name: 'rand', version: '0.8.5' }]);
  });

  it('ignores a table that follows [[package]] but is not a package', () => {
    expect(parseCargoLock(lock).map((d) => d.name)).not.toContain('not-a-package');
  });

  it('keeps every locked version of a crate', () => {
    const multi =
      `[[package]]\nname = "syn"\nversion = "1.0.109"\nsource = "${CRATES_IO}"\n\n` +
      `[[package]]\nname = "syn"\nversion = "2.0.50"\nsource = "${CRATES_IO}"\n`;
    expect(parseCargoLock(multi)).toHaveLength(2);
  });

  it('returns nothing for an empty or malformed file', () => {
    expect(parseCargoLock('')).toEqual([]);
    expect(parseCargoLock('[[package]]\nname = "x"\n')).toEqual([]);
  });
});

describe('collectRustDeps with Cargo.lock', () => {
  it('lets the lockfile exact version win over the Cargo.toml requirement in the same directory', async () => {
    const toml = `[package]\nname = "app"\n[dependencies]\nserde = "1.0"\nregex = "1"\n`;
    // Cargo.toml listed first on purpose: the lock must still win.
    const oct = octokitWith({ 'Cargo.toml': toml, 'Cargo.lock': lock });
    const deps = await collectRustDeps(oct, 'o', 'r', ['Cargo.toml', 'Cargo.lock']);
    expect(deps.find((d) => d.name === 'serde')?.version).toBe('1.0.197');
    expect(deps.find((d) => d.name === 'regex')?.version).toBe('1');
    expect(deps.map((d) => d.name).sort()).toEqual(['regex', 'serde', 'tokio']);
  });

  it('keeps root-first ordering across directories', async () => {
    const rootToml = `[dependencies]\nserde = "1.0"\n`;
    const memberLock = `[[package]]\nname = "serde"\nversion = "1.0.1"\nsource = "${CRATES_IO}"\n`;
    const oct = octokitWith({ 'Cargo.toml': rootToml, 'crate-a/Cargo.lock': memberLock });
    const deps = await collectRustDeps(oct, 'o', 'r', ['Cargo.toml', 'crate-a/Cargo.lock']);
    expect(deps).toEqual([{ name: 'serde', version: '1.0' }]);
  });

  it('does not read Cargo.lock as a workspace.dependencies source', async () => {
    const oct = octokitWith({ 'Cargo.lock': lock });
    const deps = await collectRustDeps(oct, 'o', 'r', ['Cargo.lock']);
    expect(deps).toEqual([
      { name: 'serde', version: '1.0.197' },
      { name: 'tokio', version: '1.36.0' },
    ]);
  });
});
