/**
 * Unit tests for the pure yarn.lock (v1 classic) helpers and the
 * cross-format merge helper in lib/manifest-discovery.ts.
 *
 * The I/O wrapper (fetchYarnLockfileResolutions) and its end-to-end wiring
 * into collectDeps are covered by tests/unit/osv-lockfile.test.ts.
 *
 * discoverYarnLockfilePaths:
 *   - always includes repo-root yarn.lock
 *   - includes co-located lockfile next to each discovered package.json
 *   - deduplicates (root manifest → no duplicate root lockfile entry)
 *
 * parseYarnLockfileContentsList:
 *   - single unscoped descriptor
 *   - scoped package (@scope/name)
 *   - multiple comma-separated descriptors in one block resolve to the same version
 *   - a name resolving to the SAME version across multiple entries is kept
 *   - a name resolving to DISTINCT versions across blocks is dropped entirely
 *     (D-006: ambiguity degrades to the manifest floor, not lowest-wins)
 *   - empty list → empty map
 *   - comments and blank lines ignored
 *   - CRLF-terminated content parses the same as LF
 *   - berry (yarn v2+) lockfile detected via `__metadata:` and skipped entirely
 *   - berry-format content WITHOUT the `__metadata:` marker still degrades to
 *     an empty map (defense in depth: the v1 `version "x"` regex never
 *     matches berry's `version: x` field syntax either)
 *   - block with no `version` field is skipped
 *   - first-match-wins for `version` within a block, not a later field of the
 *     same name nested under `dependencies:` (mirrors the poetry.lock
 *     sub-table protection in python-lockfile.test.ts)
 *   - a comma inside a quoted descriptor's own range does not corrupt the name
 *
 * mergeLockfileResolutions:
 *   - single map passthrough
 *   - agreement across two maps for the same name is kept
 *   - disagreement across two maps for the same name drops that name
 *     (D-006: ambiguity degrades to the manifest floor, not lowest-wins)
 *   - a name present in only one map is used as-is
 */

import { describe, it, expect } from 'vitest';

import {
  discoverYarnLockfilePaths,
  mergeLockfileResolutions,
  parseYarnLockfileContentsList,
} from '@/lib/manifest-discovery';

// ============================================================================
// discoverYarnLockfilePaths
// ============================================================================

describe('discoverYarnLockfilePaths', () => {
  it('always includes the repo-root yarn.lock', () => {
    expect(discoverYarnLockfilePaths([])).toContain('yarn.lock');
  });

  it('deduplicates when package.json is at the root (same as root lockfile)', () => {
    const paths = discoverYarnLockfilePaths(['package.json']);
    expect(paths).toEqual(['yarn.lock']); // only one entry
  });

  it('adds a co-located lockfile for each non-root manifest', () => {
    const paths = discoverYarnLockfilePaths(['packages/a/package.json']);
    expect(paths).toContain('yarn.lock');
    expect(paths).toContain('packages/a/yarn.lock');
    expect(paths).toHaveLength(2);
  });

  it('handles multiple workspace manifests without duplicates', () => {
    const paths = discoverYarnLockfilePaths([
      'package.json',
      'packages/a/package.json',
      'packages/b/package.json',
    ]);
    expect(paths).toContain('yarn.lock');
    expect(paths).toContain('packages/a/yarn.lock');
    expect(paths).toContain('packages/b/yarn.lock');
    expect(paths).toHaveLength(3); // root + a + b (root already covered by package.json)
  });
});

// ============================================================================
// parseYarnLockfileContentsList
// ============================================================================

describe('parseYarnLockfileContentsList', () => {
  it('returns an empty map for an empty content list', () => {
    expect(parseYarnLockfileContentsList([])).toEqual(new Map());
  });

  it('parses a single unscoped descriptor block', () => {
    const content = [
      '# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.',
      '# yarn lockfile v1',
      '',
      'glob@^10.3.0:',
      '  version "10.5.0"',
      '  resolved "https://registry.yarnpkg.com/glob/-/glob-10.5.0.tgz#deadbeef"',
      '  integrity sha512-abc123==',
      '  dependencies:',
      '    foreground-child "^3.1.0"',
      '',
    ].join('\n');
    const map = parseYarnLockfileContentsList([content]);
    expect(map.get('glob')).toBe('10.5.0');
  });

  it('parses a scoped package (@scope/name)', () => {
    const content = [
      '"@babel/code-frame@^7.0.0":',
      '  version "7.24.0"',
      '  resolved "https://registry.yarnpkg.com/@babel/code-frame/-/code-frame-7.24.0.tgz#x"',
      '',
    ].join('\n');
    const map = parseYarnLockfileContentsList([content]);
    expect(map.get('@babel/code-frame')).toBe('7.24.0');
  });

  it('resolves multiple comma-separated descriptors in one block to the same version', () => {
    const content = [
      '"@babel/code-frame@^7.0.0", "@babel/code-frame@^7.12.13":',
      '  version "7.24.0"',
      '  resolved "https://registry.yarnpkg.com/@babel/code-frame/-/code-frame-7.24.0.tgz#x"',
      '',
    ].join('\n');
    const map = parseYarnLockfileContentsList([content]);
    // Only one distinct name in this block, but confirms the multi-descriptor
    // header line is parsed without breaking.
    expect(map.get('@babel/code-frame')).toBe('7.24.0');
  });

  it('unscoped multi-descriptor header (repeated ranges of the SAME package) resolves to that version', () => {
    // Real yarn.lock headers only ever repeat ranges of the SAME package in
    // one block (yarn dedupes distinct packages into distinct blocks), so
    // this fixture intentionally has only one distinct name — it exercises
    // the multi-descriptor header-parsing path, not a multi-name scenario.
    const content = [
      'lodash@^4.0.0, lodash@^4.17.0:',
      '  version "4.17.21"',
      '  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz#x"',
      '',
    ].join('\n');
    const map = parseYarnLockfileContentsList([content]);
    expect(map.get('lodash')).toBe('4.17.21');
  });

  it('keeps a resolved version when the same package appears in multiple blocks agreeing on the same version', () => {
    const content = [
      'glob@^10.3.0:',
      '  version "10.5.0"',
      '  resolved "x"',
      '',
      'glob@^10.4.0:',
      '  version "10.5.0"',
      '  resolved "x"',
      '',
    ].join('\n');
    const map = parseYarnLockfileContentsList([content]);
    expect(map.get('glob')).toBe('10.5.0');
  });

  it('keeps a resolved version that agrees across MULTIPLE lockfile content strings', () => {
    const rootLock = ['lodash@^4.0.0:', '  version "4.17.21"', '  resolved "x"', ''].join('\n');
    const packageLock = ['lodash@^4.0.0:', '  version "4.17.21"', '  resolved "x"', ''].join('\n');
    const map = parseYarnLockfileContentsList([rootLock, packageLock]);
    expect(map.get('lodash')).toBe('4.17.21');
  });

  it('D-006: drops a name entirely when it resolves to DISTINCT versions across blocks (floor fallback, not lowest-wins)', () => {
    // A real scenario a keyed-by-bare-name map can't disambiguate: the
    // manifest declares glob@^10.3.0 directly, but an unrelated transitive
    // block also pins glob, at a lower major (^7.x), resolved to 7.2.3. A
    // naive lowest-wins map would silently report glob as resolved to 7.2.3
    // (an unrelated package's resolution), which is a FALSE NEGATIVE for any
    // CVE affecting the real (10.x) installed glob. The fix: when a bare name
    // has more than one distinct resolved version, drop it from the map so
    // the caller falls back to the manifest floor (10.3.0) instead — the
    // finding is NOT falsely cleared.
    const content = [
      'glob@^7.1.6:',
      '  version "7.2.3"',
      '  resolved "x"',
      '  dependencies:',
      '    inflight "^1.0.4"',
      '',
      'glob@^10.3.0:',
      '  version "10.4.0"',
      '  resolved "x"',
      '',
    ].join('\n');
    const map = parseYarnLockfileContentsList([content]);
    expect(map.has('glob')).toBe(false);
  });

  it('D-006: distinct-version drop also applies across MULTIPLE lockfile content strings', () => {
    const rootLock = ['lodash@^4.0.0:', '  version "4.17.21"', '  resolved "x"', ''].join('\n');
    const packageLock = ['lodash@^4.0.0:', '  version "4.14.0"', '  resolved "x"', ''].join('\n');
    const map = parseYarnLockfileContentsList([rootLock, packageLock]);
    expect(map.has('lodash')).toBe(false);
  });

  it('ignores comments and blank lines', () => {
    const content = [
      '# yarn lockfile v1',
      '',
      '',
      'semver@^7.0.0:',
      '  version "7.6.3"',
      '  resolved "x"',
      '',
    ].join('\n');
    const map = parseYarnLockfileContentsList([content]);
    expect(map.get('semver')).toBe('7.6.3');
  });

  it('detects a berry (yarn v2+) lockfile via __metadata and skips it entirely', () => {
    const berryContent = [
      '# This file is generated by running "yarn install" inside your project in a Yarn workspace.',
      '__metadata:',
      '  version: 6',
      '  cacheKey: 8',
      '',
      '"glob@npm:^10.3.0":',
      '  version: 10.5.0',
      '  resolution: "glob@npm:10.5.0"',
      '',
    ].join('\n');
    const map = parseYarnLockfileContentsList([berryContent]);
    expect(map.size).toBe(0);
  });

  it('degrades to an empty map for berry-format content even WITHOUT the __metadata: marker (defense in depth)', () => {
    // Belt-and-suspenders: even if the __metadata: marker were missing or the
    // detection check were bypassed, berry's `version: x.y.z` field syntax
    // (colon, unquoted) never matches this parser's v1 `version "x.y.z"`
    // regex, so the block is treated as header-only (no version found) rather
    // than being mis-parsed as a v1 resolution.
    const berryContentNoMarker = [
      '"glob@npm:^10.3.0":',
      '  version: 10.5.0',
      '  resolution: "glob@npm:10.5.0"',
      '',
    ].join('\n');
    const map = parseYarnLockfileContentsList([berryContentNoMarker]);
    expect(map.size).toBe(0);
  });

  it('parses a CRLF-terminated yarn.lock content string the same as LF', () => {
    const content = [
      'glob@^10.3.0:',
      '  version "10.5.0"',
      '  resolved "x"',
      '',
    ].join('\r\n');
    const map = parseYarnLockfileContentsList([content]);
    expect(map.get('glob')).toBe('10.5.0');
  });

  it('skips a block with no version field (malformed / truncated entry)', () => {
    const content = [
      'weird-package@^1.0.0:',
      '  resolved "x"',
      '',
      'normal@^1.0.0:',
      '  version "1.2.3"',
      '  resolved "x"',
      '',
    ].join('\n');
    const map = parseYarnLockfileContentsList([content]);
    expect(map.has('weird-package')).toBe(false);
    expect(map.get('normal')).toBe('1.2.3');
  });

  it('keeps the first version field in a block, not a later one nested under dependencies: (mirrors the poetry.lock sub-table protection)', () => {
    // A transitive dependency in the `dependencies:` section literally named
    // "version" (an unusual but valid npm package name) would, under a
    // last-match-wins parser, overwrite the block's real `version` field and
    // silently corrupt the resolved version — exactly what first-match-wins
    // guards against (see python-lockfile.test.ts's analogous poetry.lock
    // sub-table test).
    const content = [
      'foo@^1.0.0:',
      '  version "1.2.3"',
      '  resolved "x"',
      '  dependencies:',
      '    version "^3.0.0"',
      '',
    ].join('\n');
    const map = parseYarnLockfileContentsList([content]);
    expect(map.get('foo')).toBe('1.2.3');
  });

  it('does not corrupt a descriptor name when its quoted range contains a comma', () => {
    // A version range like ">=1.0.0, <2.0.0" contains a comma inside the
    // quoted descriptor itself. Splitting on every comma unconditionally
    // (before quote-stripping) would tear this into a dangling `"lodash` key
    // and a stray ` <2.0.0"` token instead of the single name `lodash`.
    const content = [
      '"lodash@>=1.0.0, <2.0.0":',
      '  version "1.9.9"',
      '  resolved "x"',
      '',
    ].join('\n');
    const map = parseYarnLockfileContentsList([content]);
    expect(map.get('lodash')).toBe('1.9.9');
    expect(map.size).toBe(1); // no corrupt extra key from the torn-apart comma
  });
});

// ============================================================================
// mergeLockfileResolutions
// ============================================================================

describe('mergeLockfileResolutions', () => {
  it('passes through a single map unchanged', () => {
    const map = new Map([['glob', '10.5.0']]);
    expect(mergeLockfileResolutions([map])).toEqual(new Map([['glob', '10.5.0']]));
  });

  it('AGREE: keeps the version when both maps agree on it for the same package (e.g. npm + yarn)', () => {
    const npmMap = new Map([['glob', '10.5.0']]);
    const yarnMap = new Map([['glob', '10.5.0']]);
    const merged = mergeLockfileResolutions([npmMap, yarnMap]);
    expect(merged.get('glob')).toBe('10.5.0');
  });

  it('D-006 DISAGREE: drops a name entirely when the two maps disagree on its version (floor fallback, not lowest-wins or npm-precedence)', () => {
    // A stale package-lock.json left over from a package-manager migration
    // can carry a HIGHER version than the yarn.lock that reflects the real
    // install, so neither "npm wins" nor "lower wins" is safe in general:
    // both can mask the real, yarn-resolved vulnerable version behind a
    // stale, safer-looking npm one. Drop to the floor instead.
    const npmMap = new Map([['glob', '10.5.0']]);
    const yarnMap = new Map([['glob', '10.3.1']]);
    const merged = mergeLockfileResolutions([npmMap, yarnMap]);
    expect(merged.has('glob')).toBe(false);
  });

  it('ONE-SIDED: unions disjoint entries from both maps, using the only map that has each name', () => {
    const npmMap = new Map([['glob', '10.5.0']]);
    const yarnMap = new Map([['lodash', '4.17.21']]);
    const merged = mergeLockfileResolutions([npmMap, yarnMap]);
    expect(merged.get('glob')).toBe('10.5.0');
    expect(merged.get('lodash')).toBe('4.17.21');
  });

  it('returns an empty map when all inputs are empty', () => {
    expect(mergeLockfileResolutions([new Map(), new Map()])).toEqual(new Map());
  });
});
