/**
 * Unit tests for the pure yarn.lock (v1 classic) helpers and the
 * cross-format merge helper in lib/manifest-discovery.ts.
 *
 * The I/O wrapper (fetchYarnLockfileResolutions) and its end-to-end wiring
 * into collectDeps are covered by tests/unit/osv-lockfile.test.ts.
 *
 * discoverYarnLockfilePaths:
 *   - always includes repo-root yarn.lock
 *   - includes co-located lockfile next to each discovered package.json
 *   - deduplicates (root manifest → no duplicate root lockfile entry)
 *
 * parseYarnLockfileContentsList:
 *   - single unscoped descriptor
 *   - scoped package (@scope/name)
 *   - multiple comma-separated descriptors in one block resolve to the same version
 *   - LOWEST resolved version kept across multiple entries (security-conservative)
 *   - empty list → empty map
 *   - comments and blank lines ignored
 *   - berry (yarn v2+) lockfile detected via `__metadata:` and skipped entirely
 *   - block with no `version` field is skipped
 *
 * mergeLockfileResolutions:
 *   - single map passthrough
 *   - lowest-wins across two maps (e.g. npm + yarn resolutions for the same repo)
 */

import { describe, it, expect } from 'vitest';

import {
  discoverYarnLockfilePaths,
  mergeLockfileResolutions,
  parseYarnLockfileContentsList,
} from '@/lib/manifest-discovery';

// ============================================================================
// discoverYarnLockfilePaths
// ============================================================================

describe('discoverYarnLockfilePaths', () => {
  it('always includes the repo-root yarn.lock', () => {
    expect(discoverYarnLockfilePaths([])).toContain('yarn.lock');
  });

  it('deduplicates when package.json is at the root (same as root lockfile)', () => {
    const paths = discoverYarnLockfilePaths(['package.json']);
    expect(paths).toEqual(['yarn.lock']); // only one entry
  });

  it('adds a co-located lockfile for each non-root manifest', () => {
    const paths = discoverYarnLockfilePaths(['packages/a/package.json']);
    expect(paths).toContain('yarn.lock');
    expect(paths).toContain('packages/a/yarn.lock');
    expect(paths).toHaveLength(2);
  });

  it('handles multiple workspace manifests without duplicates', () => {
    const paths = discoverYarnLockfilePaths([
      'package.json',
      'packages/a/package.json',
      'packages/b/package.json',
    ]);
    expect(paths).toContain('yarn.lock');
    expect(paths).toContain('packages/a/yarn.lock');
    expect(paths).toContain('packages/b/yarn.lock');
    expect(paths).toHaveLength(3); // root + a + b (root already covered by package.json)
  });
});

// ============================================================================
// parseYarnLockfileContentsList
// ============================================================================

describe('parseYarnLockfileContentsList', () => {
  it('returns an empty map for an empty content list', () => {
    expect(parseYarnLockfileContentsList([])).toEqual(new Map());
  });

  it('parses a single unscoped descriptor block', () => {
    const content = [
      '# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.',
      '# yarn lockfile v1',
      '',
      'glob@^10.3.0:',
      '  version "10.5.0"',
      '  resolved "https://registry.yarnpkg.com/glob/-/glob-10.5.0.tgz#deadbeef"',
      '  integrity sha512-abc123==',
      '  dependencies:',
      '    foreground-child "^3.1.0"',
      '',
    ].join('\n');
    const map = parseYarnLockfileContentsList([content]);
    expect(map.get('glob')).toBe('10.5.0');
  });

  it('parses a scoped package (@scope/name)', () => {
    const content = [
      '"@babel/code-frame@^7.0.0":',
      '  version "7.24.0"',
      '  resolved "https://registry.yarnpkg.com/@babel/code-frame/-/code-frame-7.24.0.tgz#x"',
      '',
    ].join('\n');
    const map = parseYarnLockfileContentsList([content]);
    expect(map.get('@babel/code-frame')).toBe('7.24.0');
  });

  it('resolves multiple comma-separated descriptors in one block to the same version', () => {
    const content = [
      '"@babel/code-frame@^7.0.0", "@babel/code-frame@^7.12.13":',
      '  version "7.24.0"',
      '  resolved "https://registry.yarnpkg.com/@babel/code-frame/-/code-frame-7.24.0.tgz#x"',
      '',
    ].join('\n');
    const map = parseYarnLockfileContentsList([content]);
    // Only one distinct name in this block, but confirms the multi-descriptor
    // header line is parsed without breaking.
    expect(map.get('@babel/code-frame')).toBe('7.24.0');
  });

  it('unscoped multi-descriptor header maps all listed names to the same version', () => {
    const content = [
      'lodash@^4.0.0, lodash@^4.17.0:',
      '  version "4.17.21"',
      '  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz#x"',
      '',
    ].join('\n');
    const map = parseYarnLockfileContentsList([content]);
    expect(map.get('lodash')).toBe('4.17.21');
  });

  it('keeps the LOWEST resolved version when the same package appears in multiple blocks (security-conservative)', () => {
    const content = [
      'glob@^10.3.0:',
      '  version "10.5.0"',
      '  resolved "x"',
      '',
      'glob@^9.0.0:',
      '  version "9.3.5"',
      '  resolved "x"',
      '',
    ].join('\n');
    const map = parseYarnLockfileContentsList([content]);
    expect(map.get('glob')).toBe('9.3.5');
  });

  it('keeps the lowest version across MULTIPLE lockfile content strings', () => {
    const rootLock = ['lodash@^4.0.0:', '  version "4.17.21"', '  resolved "x"', ''].join('\n');
    const packageLock = ['lodash@^4.0.0:', '  version "4.14.0"', '  resolved "x"', ''].join('\n');
    const map = parseYarnLockfileContentsList([rootLock, packageLock]);
    expect(map.get('lodash')).toBe('4.14.0');
  });

  it('ignores comments and blank lines', () => {
    const content = [
      '# yarn lockfile v1',
      '',
      '',
      'semver@^7.0.0:',
      '  version "7.6.3"',
      '  resolved "x"',
      '',
    ].join('\n');
    const map = parseYarnLockfileContentsList([content]);
    expect(map.get('semver')).toBe('7.6.3');
  });

  it('detects a berry (yarn v2+) lockfile via __metadata and skips it entirely', () => {
    const berryContent = [
      '# This file is generated by running "yarn install" inside your project in a Yarn workspace.',
      '__metadata:',
      '  version: 6',
      '  cacheKey: 8',
      '',
      '"glob@npm:^10.3.0":',
      '  version: 10.5.0',
      '  resolution: "glob@npm:10.5.0"',
      '',
    ].join('\n');
    const map = parseYarnLockfileContentsList([berryContent]);
    expect(map.size).toBe(0);
  });

  it('skips a block with no version field (malformed / truncated entry)', () => {
    const content = [
      'weird-package@^1.0.0:',
      '  resolved "x"',
      '',
      'normal@^1.0.0:',
      '  version "1.2.3"',
      '  resolved "x"',
      '',
    ].join('\n');
    const map = parseYarnLockfileContentsList([content]);
    expect(map.has('weird-package')).toBe(false);
    expect(map.get('normal')).toBe('1.2.3');
  });
});

// ============================================================================
// mergeLockfileResolutions
// ============================================================================

describe('mergeLockfileResolutions', () => {
  it('passes through a single map unchanged', () => {
    const map = new Map([['glob', '10.5.0']]);
    expect(mergeLockfileResolutions([map])).toEqual(new Map([['glob', '10.5.0']]));
  });

  it('keeps the LOWEST version across two maps for the same package (e.g. npm + yarn)', () => {
    const npmMap = new Map([['glob', '10.5.0']]);
    const yarnMap = new Map([['glob', '10.3.1']]);
    const merged = mergeLockfileResolutions([npmMap, yarnMap]);
    expect(merged.get('glob')).toBe('10.3.1');
  });

  it('unions disjoint entries from both maps', () => {
    const npmMap = new Map([['glob', '10.5.0']]);
    const yarnMap = new Map([['lodash', '4.17.21']]);
    const merged = mergeLockfileResolutions([npmMap, yarnMap]);
    expect(merged.get('glob')).toBe('10.5.0');
    expect(merged.get('lodash')).toBe('4.17.21');
  });

  it('returns an empty map when all inputs are empty', () => {
    expect(mergeLockfileResolutions([new Map(), new Map()])).toEqual(new Map());
  });
});
